config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root "locations#index"

  # Locations management
  get "locations", to: "locations#index"
  post "search", to: "locations#search"

  # Current weather and forecasting pages
  get "weather/:id", to: "forecast#current", as: "current_weather"
  get "weather/:id/extended", to: "forecast#extended", as: "extended_weather"

  # Sidekiq UI for inspecting jobs
  if Rails.env.development? || ENV["SIDEKIQ_WEB_ENABLED"] == "true"
    mount Sidekiq::Web => "/_sidekiq"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
# Location contains the geocoded data for an address or a city:
#
# - external_id - reference to the resource in the external service / api
# - city, state, country, zipcode - basic location info
# - utc_offset - to display the time at the location
# - lat, lon - coordinates for the forecasting
#
class Location < ApplicationRecord
  STALE_THRESHOLD = 5.minutes.to_i

  has_one :weather_point, dependent: :delete

  validates :external_id, presence: true, uniqueness: { case_sensitive: false }
  validates :city, :state, :country, :lat, :lon, presence: true

  scope :recent, -> { includes(:weather_point).order(last_sync_at: :desc) }
  scope :stale, -> { where(last_sync_at: nil).or(where("last_sync_at < ?", Time.current - STALE_THRESHOLD)) }

  # Display name does not care about country for simplicity
  def display_name
    "#{city}, #{state}"
  end

  # Return latitude,longitude point
  def latlon
    [lat, lon]
  end

  # Determines if location weather data should be updated
  def should_sync?
    last_sync_at.nil? || Time.current - last_sync_at > STALE_THRESHOLD
  end

  # Trigger resync of weather data
  def schedule_sync
    Locations::CurrentForecastJob.perform_later(self.id)
    Locations::ExtendedForecastJob.perform_later(self.id)
  end
end

app/models/weather_point.rb
# Weather point contains the basic weather data for the current and extended forecasts:
#
# - external_id - reference for the resource in the external service
# - lat,log - coordinates of the location
# - temp (current, min, max)
# - pressure
# - humidity
#
class WeatherPoint < ApplicationRecord
  belongs_to :location

  validates :external_id, presence: true
  validates :temp, :pressure, :visibility, :wind_speed, :ts, presence: true

  def timestamp
    @timestamp ||= Time.at(ts, in: utc_offset)
  end

  def sunrise_timestamp
    @sunrise_timestamp ||= Time.at(sunrise_ts, in: utc_offset)
  end

  def sunset_timestamp
    @sunset_timestamp ||= Time.at(sunset_ts, in: utc_offset)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CoreServices
end

app/controllers/concerns/core_services.rb
module CoreServices
  extend ActiveSupport::Concern

  def geocoder_service
    @_geocoder_service ||= GeocoderService.new
  end

  def forecasting_service
    @_forecasting_service ||= ForecastService.new(@location)
  end
end

app/controllers/forecast_controller.rb
class ForecastController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_to_home
  before_action :require_location

  # Display current (and extended) weather at location
  # GET /weather/:id
  def current
    # All our current weather data is cached BY DEFAULT, ie when we sync with the
    # weather service, we cache the raw data first (so it could be queried/retried),
    #
    # then save the record holding the current data.
    # These weather points get updated automatically in the background.
    #
    @point, @cached = Cache.wrap("current", @location.id, ttl: 30.minutes) do
      @location.weather_point
    end

    # We do not fetch the extended forecast data by default. When location needs to
    # be refreshed, we grab the extended forecast and cache it for 24 hours or
    # until the next location refresh.
    @extended = load_extended_forecast
  end

  # Display extended weather forecast (5day/3h)
  # GET /weather/:id/extended
  def extended
    @extended = load_extended_forecast
  end

  private

  def require_location
    @location = Location.includes(:weather_point).find(params[:id])
  end

  def redirect_to_home
    redirect_to root_path, flash: { error: I18n.t("locations.not_found") }
  end

  def load_extended_forecast
    Cache.read("extended_forecast", @location.id)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :require_search_query, only: [:search]

  # Display recently added locations
  # GET /
  # GET /locations
  def index
    @recent_locations = Location.recent.limit(10)
  end

  # Search locations by city, address or zipcode
  # POST /search
  def search
    # Fetch geolocation for the given address query.
    #
    # NOTE: we're always picking the first matched result here, so if geocoder is wrong we'll have to
    # supply a different query to be more precise.
    #
    geocode_entry = geocoder_service.geocode(@query)
    if !geocode_entry
      return redirect_to root_path, flash: { error: I18n.t("locations.not_found") }
    end

    # Manage location import and associated tasks (weather data sync, etc)
    location = LocationService.import(geocode_entry)
    unless location.persisted? && location.valid?
      return redirect_to root_path, flash: { error: I18n.t("locations.invalid") }
    end

    redirect_to current_weather_path(location)
  end

  private

  def search_params
    params.require(:search).permit(:address)
  end

  # Require the actual search query or redirect back home
  def require_search_query
    @query = search_params[:address]&.strip
    if @query.blank?
      redirect_to locations_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def render_flash_messages
    return if flash.empty?

    items = []

    flash.each do |key, value|
      key = "danger" if key == "error"
      items << content_tag(:div, class: "alert alert-#{key}") do
        content_tag(:div, class: "container text-center") { value }
      end
    end

    flash.discard
    items.join.html_safe
  end
end

app/helpers/time_format_helper.rb
module TimeFormatHelper
  def format_time(t)
    t.strftime("%l:%M %P")
  end

  def format_time_with_day(t)
    t.strftime("%a, %l %P")
  end
end

app/views/forecast/current.html.erb
<% if @location.last_sync_at %>
  <%= render "forecast/widgets/current", location: @location, point: @point, cached: @cached %>
  <%= render "forecast/widgets/today", location: @location, point: @point %>

  <% if @extended %>
    <%= render "forecast/widgets/extended", items: @extended %>
  <% else %>
    <div class="text-center">
      <%= link_to "View extended forecast", extended_weather_path(@location) %>
    </div>
  <% end %>
<% else %>
  <%= render "forecast/widgets/syncing", location: @location %>
  <script>
    // Auto-reload the page to display the loaded location data
    // NOTE: Inlining for simplicity
    setTimeout(() => { window.location.reload(); }, 2000)
  </script>
<% end %>

app/views/forecast/extended.html.erb
<h2><%= @location.display_name %></h2>

<div class="row g2">
  <div class="col-auto">
    <p>Extended forecast for the next 5 days with 3 hour window</p>
  </div>
  <div class="col text-end">
    <%= link_to "Go Back", current_weather_path(@location) %>
  </div>
</div>

<% if @extended %>
  <%= render "forecast/widgets/extended", items: @extended %>
<% else %>
  <div class="card">
    <div class="card-body">
      <div class="text-muted text-center">Sorry, extended forecast is not available.</div>
    </div>
  </div>
<% end %>

app/views/forecast/widgets/_current.html.erb
<div class="card forecast current">
  <div class="card-body">
    <div class="row">
      <div class="col-8">
        <h5 class="card-title">
          <%= location.city %>, <%= location.state %>
          as of <%= format_time(point.timestamp) %>
        </h5>
      </div>
      <div class="col-4 text-muted text-end">
        <% if cached %>
          <span class="badge rounded-pill text-bg-secondary">CACHED</span>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-8">
        <div class="display-2"><%= point.temp %>&deg;</div>
        <div class="h3"><%= point.condition %></div>
        <div class="h5">
          Day <%= point.temp_max %>&deg; <span class="text-muted"> &mdash; </span>
          Night <%= point.temp_min %>&deg;
        </div>
      </div>
      <div class="col-4 text-center">
        <div class="weather-icon large" style="background-image: url('http://openweathermap.org/img/wn/<%= point.condition_code %>@4x.png');"></div>
      </div>
    </div>
  </div>
</div>

app/views/forecast/widgets/_extended.html.erb
<div class="card forecast extended">
  <div class="card-body">
    <h5 class="card-title">Extended Forecast</h5>
    <% items.group_by { |d| d.timestamp.day }.each_pair do |_, points| %>
      <% points.each do |point| %>
        <div class="row">
          <div class="col-3"><%= format_time_with_day point.timestamp %></div>
          <div class="col-2">
            <div class="h4"><%= point.temp %>&deg;</div>
          </div>
          <div class="col-1">
            <div class="weather-icon small" style="background-image: url('http://openweathermap.org/img/wn/<%= point.condition_code %>.png');"></div>
          </div>
          <div class="col-2">
            <%= point.condition %>
          </div>
          <div class="col-3">
            <%= point.humidity %>% <span class="text-muted">humid</span>
          </div>
        </div>
      <% end %>
      <hr/>
    <% end %>
  </div>
</div>

app/views/forecast/widgets/_syncing.html.erb
<div class="card forecast current">
  <div class="card-body">
    <h5 class="card-title">
      <%= location.city %>, <%= location.state %>
    </h5>
    <hr/>
    <div class="text-center">
      <div class="spinner-border" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
      <div class="p-3">
        Please wait while we are fetching weather details...
      </div>
    </div>
  </div>
</div>

app/views/forecast/widgets/_today.html.erb
<div class="card forecast today">
  <div class="card-body">
    <div class="row">
      <div class="col">
        <h5 class="card-title">Weather Today</h5>
      </div>
      <div class="col-4 text-muted text-end">
        <%= time_ago_in_words location.last_sync_at %> ago
      </div>
    </div>
    <div class="row">
      <div class="col-3">
        <p class="h3"><%= point.temp %>&deg;</p>
        <p class="text-muted">Current</p>
      </div>
      <div class="col-3">
        <p class="h3"><%= point.temp_feels_like %>&deg;</p>
        <p class="text-muted">Feels Like</p>
      </div>
      <div class="col">
        <p class="h3">
          <%= format_time point.sunrise_timestamp %>
        </p>
        <p class="text-muted">Sunrise</p>
      </div>
      <div class="col">
        <p class="h3">
          <%= format_time point.sunset_timestamp %>
        </p>
        <p class="text-muted">Sunset</p>
      </div>
    </div>
    <ul class="list-group">
      <li class="list-group-item">
        <div class="row">
          <div class="col"><strong>High / Low</strong></div>
          <div class="col text-end"><%= point.temp_min %>&deg; / <%= point.temp_max %>&deg;</div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="row">
          <div class="col"><strong>Humidity</strong></div>
          <div class="col text-end"><%= point.humidity %>%</div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="row">
          <div class="col"><strong>Wind</strong></div>
          <div class="col text-end"><%= point.wind_speed %> mph</div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="row">
          <div class="col"><strong>Visibility</strong></div>
          <div class="col text-end"><%= point.visibility / 1600 %> mi</div>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
  <head>
    <title>Weatherapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "layouts/shared/navigation" %>
    <%= render_flash_messages %>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand" href="/">Weather App</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"></li>
      </ul>
      <%= form_for :search, url: search_path, method: :post, class: "d-flex" do |f| %>
        <%= f.text_field :address, placeholder: "Search City or Zip Code", class: "form-control me-1", list: "cities" %>
        <%= f.submit "Go", class: "btn btn-outline-success" %>
        <datalist id="cities">
          <option value="San Francisco">
          <option value="New York">
          <option value="Seattle">
          <option value="Los Angeles">
          <option value="Chicago">
        </datalist>
      <% end %>
    </div>
  </div>
</nav>

app/views/locations/index.html.erb
<%= render "locations/index/search" %>

<% if @recent_locations.size > 0 %>
  <div class="mt-4">
    <%= render "locations/index/recent", locations: @recent_locations %>
  </div>
<% end %>

app/views/locations/index/_recent.html.erb
<h2>Recent Locations</h2>

<div class="row">
  <% locations.each do |loc| %>
    <div class="col-4">
      <div class="card mb-4">
        <div class="card-body">
          <div><a href="<%= current_weather_path(loc.id) %>"><%= loc.display_name %></a></div>
          <% if wp = loc.weather_point %>
            <div class="display-3"><%= wp.temp %>&deg;</div>
            <div class="row">
              <div class="col-9"><%= loc.weather_point.condition %></div>
              <div class="col-3">
                <div class="weather-icon small" style="background-image: url('http://openweathermap.org/img/wn/<%= wp.condition_code %>@4x.png');"></div>
              </div>
            </div>
          <% else %>
            <p class="text-muted">Weather N/A</p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/locations/index/_search.html.erb
<%= form_for :search, url: search_path, method: :post do |f| %>
  <h1>Get Started</h1>
  <p>Search location by City or a Zip Code to get latest weather.</p>
  <div class="row g-2">
    <div class="col-8">
      <%= f.text_field :address, placeholder: "Search City or Zip Code", class: "form-control form-control", list: "cities" %>
      <datalist id="cities">
        <option value="San Francisco">
        <option value="New York">
        <option value="Seattle">
        <option value="Los Angeles">
        <option value="Chicago">
      </datalist>
    </div>
    <div class="col-auto">
      <%= f.submit "Search", class: "btn btn-outline-primary" %>
    </div>
  </div>
<% end %>